"""Extensive PDF-based testing suite for the transcript → recommend pipeline.

Tests PDF extraction, parsing, field extraction, grade handling, transfer
credits, and the full end-to-end recommendation pipeline using synthesized
PDF transcripts generated by ``generate_fixture_pdfs.py``.

Requirements: ``reportlab>=4.0`` (in the ``dev`` extra).
"""

from __future__ import annotations

from pathlib import Path

import pytest  # type: ignore

from capstone.config import (
    AppConfig,
    CreditLimits,
    DatabaseConfig,
    RankingWeights,
    ScraperConfig,
)
from capstone.recommender import Recommender
from capstone.transcript.models import CompletedCourse, Transcript
from capstone.transcript.parser import parse_transcript

import sys

sys.path.insert(0, str(Path(__file__).parent))
from generate_fixture_pdfs import generate_all, ALL_GENERATORS  # type: ignore # noqa


# ── Fixtures ────────────────────────────────────────────────────────────────


@pytest.fixture(scope="session")
def pdf_dir(tmp_path_factory):
    """Generate all fixture PDFs once per session into a temp directory."""
    out = tmp_path_factory.mktemp("fixture_pdfs")
    generate_all(out)
    return out


@pytest.fixture
def default_config() -> AppConfig:
    return AppConfig(
        scraper=ScraperConfig(),
        database=DatabaseConfig(),
        ranking_weights=RankingWeights(),
        credit_limits=CreditLimits(default=15, hard_ceiling=25),
    )


# ── Test Class: PDF Parsing ─────────────────────────────────────────────────


class TestPDFParsing:
    """Every generated PDF fixture must parse into a valid Transcript."""

    @pytest.mark.parametrize("name", list(ALL_GENERATORS.keys()))
    def test_every_fixture_parses_successfully(self, pdf_dir, name):
        pdf = pdf_dir / f"{name}.pdf"
        assert pdf.exists(), f"Fixture PDF {name}.pdf was not generated"
        transcript = parse_transcript(pdf)
        assert isinstance(transcript, Transcript)

    @pytest.mark.parametrize("name", list(ALL_GENERATORS.keys()))
    def test_every_fixture_has_completed_courses(self, pdf_dir, name):
        transcript = parse_transcript(pdf_dir / f"{name}.pdf")
        assert (
            len(transcript.completed) > 0
        ), f"{name}: expected at least one completed course"

    @pytest.mark.parametrize("name", list(ALL_GENERATORS.keys()))
    def test_no_parse_errors_on_grade_field(self, pdf_dir, name):
        transcript = parse_transcript(pdf_dir / f"{name}.pdf")
        valid_grades = {"CR", "NC", "W", "S", "I", "IP", "N", "HW", "HP", "P"}
        for c in transcript.completed:
            if c.grade not in valid_grades:
                # Must be a numeric grade
                try:
                    float(c.grade)
                except ValueError:
                    pytest.fail(f"{name}: invalid grade '{c.grade}' for {c.course_id}")


# ── Test Class: CSSE Junior Transcript ──────────────────────────────────────


class TestCSSEJuniorTranscript:
    """Detailed field extraction tests for the standard CSSE junior PDF."""

    def _parse(self, pdf_dir):
        return parse_transcript(pdf_dir / "csse_junior.pdf")

    def test_student_name(self, pdf_dir):
        t = self._parse(pdf_dir)
        assert t.student_name == "Krish Marpuri"

    def test_student_id(self, pdf_dir):
        t = self._parse(pdf_dir)
        assert t.student_id == "2429082"

    def test_major_detected_as_csse(self, pdf_dir):
        t = self._parse(pdf_dir)
        assert t.major == "CSSE"

    def test_campus_is_bothell(self, pdf_dir):
        t = self._parse(pdf_dir)
        assert t.campus == "Bothell"

    def test_class_standing(self, pdf_dir):
        t = self._parse(pdf_dir)
        assert t.class_standing == "JUNIOR"

    def test_current_quarter(self, pdf_dir):
        t = self._parse(pdf_dir)
        assert t.current_quarter == "SPRING QUARTER, 2026"

    def test_completed_course_count(self, pdf_dir):
        t = self._parse(pdf_dir)
        # 3 + 4 + 2 + 2 + 2 = 13 courses
        assert len(t.completed) >= 10

    def test_css142_grade(self, pdf_dir):
        t = self._parse(pdf_dir)
        css142 = next((c for c in t.completed if c.course_id == "CSS 142"), None)
        assert css142 is not None
        assert css142.grade == "3.8"
        assert css142.quarter == "AUT"
        assert css142.year == 2024

    def test_cr_grade_handled(self, pdf_dir):
        t = self._parse(pdf_dir)
        cr_courses = [c for c in t.completed if c.grade == "CR"]
        assert len(cr_courses) >= 1
        for c in cr_courses:
            assert c.is_passed

    def test_multi_word_prefix_parsed(self, pdf_dir):
        """B WRIT 134 and similar multi-word course IDs must parse."""
        t = self._parse(pdf_dir)
        cids = {c.course_id for c in t.completed}
        assert "B WRIT 134" in cids

    def test_cssskl_prefix_parsed(self, pdf_dir):
        t = self._parse(pdf_dir)
        cids = {c.course_id for c in t.completed}
        assert "CSSSKL 142" in cids

    def test_wip_courses_detected(self, pdf_dir):
        t = self._parse(pdf_dir)
        wip_ids = {c.course_id for c in t.in_progress}
        assert "CSS 382" in wip_ids
        assert "STMATH 224" in wip_ids

    def test_wip_not_in_completed(self, pdf_dir):
        t = self._parse(pdf_dir)
        completed_ids = {c.course_id for c in t.completed}
        assert "CSS 382" not in completed_ids
        assert "STMATH 224" not in completed_ids

    def test_transfer_credits_ib(self, pdf_dir):
        t = self._parse(pdf_dir)
        ib_credits = [tc for tc in t.transfer_credits if tc.source == "IB"]
        assert len(ib_credits) >= 2
        ib_ids = {tc.course_id for tc in ib_credits}
        assert "CHEM 142" in ib_ids
        assert "MATH 120" in ib_ids

    def test_placement_tests(self, pdf_dir):
        t = self._parse(pdf_dir)
        test_types = {p.test_type for p in t.placement_tests}
        assert "FYCDSP" in test_types
        assert "MTHDSP" in test_types

    def test_cumulative_gpa(self, pdf_dir):
        t = self._parse(pdf_dir)
        assert t.cumulative_gpa == pytest.approx(3.55, abs=0.01)

    def test_credits_earned(self, pdf_dir):
        t = self._parse(pdf_dir)
        assert t.total_credits_earned is not None
        assert t.total_credits_earned > 0


# ── Test Class: Freshman Minimal ────────────────────────────────────────────


class TestFreshmanMinimal:
    """Minimal transcript — 1 quarter, no transfers, no WIP."""

    def test_parses_successfully(self, pdf_dir):
        t = parse_transcript(pdf_dir / "freshman_minimal.pdf")
        assert t.student_name == "Jane Doe"
        assert t.class_standing == "FRESHMAN"

    def test_single_quarter_courses(self, pdf_dir):
        t = parse_transcript(pdf_dir / "freshman_minimal.pdf")
        assert len(t.completed) == 3

    def test_no_wip(self, pdf_dir):
        t = parse_transcript(pdf_dir / "freshman_minimal.pdf")
        assert len(t.in_progress) == 0

    def test_no_transfer_credits(self, pdf_dir):
        t = parse_transcript(pdf_dir / "freshman_minimal.pdf")
        assert len(t.transfer_credits) == 0


# ── Test Class: Senior Heavy ────────────────────────────────────────────────


class TestSeniorHeavy:
    """Senior with 30+ courses across 8 quarters, including W grades."""

    def test_parses_successfully(self, pdf_dir):
        t = parse_transcript(pdf_dir / "senior_heavy.pdf")
        assert t.student_name == "Alex Johnson"
        assert t.class_standing == "SENIOR"

    def test_many_courses(self, pdf_dir):
        t = parse_transcript(pdf_dir / "senior_heavy.pdf")
        assert len(t.completed) >= 20

    def test_withdrawn_courses(self, pdf_dir):
        t = parse_transcript(pdf_dir / "senior_heavy.pdf")
        withdrawn = [c for c in t.completed if c.grade == "W"]
        assert len(withdrawn) >= 1
        for w in withdrawn:
            assert w.is_withdrawn
            assert not w.is_passed

    def test_high_gpa(self, pdf_dir):
        t = parse_transcript(pdf_dir / "senior_heavy.pdf")
        assert t.cumulative_gpa is not None
        assert t.cumulative_gpa > 3.5


# ── Test Class: Transfer Student ────────────────────────────────────────────


class TestTransferStudent:
    """Heavy AP/IB/Running Start credits."""

    def test_parses_successfully(self, pdf_dir):
        t = parse_transcript(pdf_dir / "transfer_student.pdf")
        assert t.student_name == "Maria Garcia"

    def test_ib_credits(self, pdf_dir):
        t = parse_transcript(pdf_dir / "transfer_student.pdf")
        ib = [tc for tc in t.transfer_credits if tc.source == "IB"]
        assert len(ib) >= 3

    def test_ap_credits(self, pdf_dir):
        t = parse_transcript(pdf_dir / "transfer_student.pdf")
        ap = [tc for tc in t.transfer_credits if tc.source == "AP"]
        assert len(ap) >= 1

    def test_running_start_credits(self, pdf_dir):
        t = parse_transcript(pdf_dir / "transfer_student.pdf")
        rs = [tc for tc in t.transfer_credits if tc.source == "RUNNING_START"]
        assert len(rs) >= 1

    def test_wip_present(self, pdf_dir):
        t = parse_transcript(pdf_dir / "transfer_student.pdf")
        assert len(t.in_progress) >= 1


# ── Test Class: Math Major ──────────────────────────────────────────────────


class TestMathMajor:
    """Non-CSSE major detection."""

    def test_major_detected_as_math(self, pdf_dir):
        t = parse_transcript(pdf_dir / "math_major.pdf")
        # The parser checks for "MATHEMATICS" in header
        assert t.major == "MATH"

    def test_stmath_courses_parsed(self, pdf_dir):
        t = parse_transcript(pdf_dir / "math_major.pdf")
        stmath = [c for c in t.completed if c.course_id.startswith("STMATH")]
        assert len(stmath) >= 4


# ── Test Class: Edge Case Grades ────────────────────────────────────────────


class TestEdgeCaseGrades:
    """CR, NC, W, S, HW, HP, N all handled correctly."""

    def _parse(self, pdf_dir):
        return parse_transcript(pdf_dir / "edge_cases.pdf")

    def test_cr_grade(self, pdf_dir):
        t = self._parse(pdf_dir)
        cr = [c for c in t.completed if c.grade == "CR"]
        assert len(cr) >= 1
        for c in cr:
            assert c.is_passed

    def test_nc_grade(self, pdf_dir):
        t = self._parse(pdf_dir)
        nc = [c for c in t.completed if c.grade == "NC"]
        assert len(nc) >= 1
        for c in nc:
            assert not c.is_passed

    def test_w_grade(self, pdf_dir):
        t = self._parse(pdf_dir)
        w = [c for c in t.completed if c.grade == "W"]
        assert len(w) >= 1
        for c in w:
            assert c.is_withdrawn
            assert not c.is_passed

    def test_s_grade(self, pdf_dir):
        t = self._parse(pdf_dir)
        s = [c for c in t.completed if c.grade == "S"]
        assert len(s) >= 1
        for c in s:
            assert c.is_passed

    def test_hw_grade(self, pdf_dir):
        t = self._parse(pdf_dir)
        hw = [c for c in t.completed if c.grade == "HW"]
        assert len(hw) >= 1

    def test_hp_grade(self, pdf_dir):
        t = self._parse(pdf_dir)
        hp = [c for c in t.completed if c.grade == "HP"]
        assert len(hp) >= 1

    def test_n_grade(self, pdf_dir):
        t = self._parse(pdf_dir)
        n = [c for c in t.completed if c.grade == "N"]
        assert len(n) >= 1

    def test_repeated_course(self, pdf_dir):
        """CSS 143 appears twice — once W, once passed. Both should parse."""
        t = self._parse(pdf_dir)
        css143 = [c for c in t.completed if c.course_id == "CSS 143"]
        assert len(css143) == 2
        grades = {c.grade for c in css143}
        assert "W" in grades
        assert "2.5" in grades

    def test_bearth_prefix(self, pdf_dir):
        """BEARTH 320 has an unusual prefix that must parse."""
        t = self._parse(pdf_dir)
        cids = {c.course_id for c in t.completed}
        assert "BEARTH 320" in cids


# ── Test Class: Dense Two-Column ────────────────────────────────────────────


class TestDenseTwoColumn:
    """32 courses across 8 quarters — stress the extraction logic."""

    def test_parses_many_courses(self, pdf_dir):
        t = parse_transcript(pdf_dir / "two_column_dense.pdf")
        # 8 quarters × 4 courses = 32 expected
        assert len(t.completed) >= 25, f"Expected 25+ courses, got {len(t.completed)}"

    def test_class_standing(self, pdf_dir):
        t = parse_transcript(pdf_dir / "two_column_dense.pdf")
        assert t.class_standing == "SENIOR"


# ── Test Class: End-to-End Recommendation ───────────────────────────────────


class TestEndToEndRecommendation:
    """PDF → parse → recommend pipeline — hard constraints hold."""

    def test_csse_junior_gets_recommendations(
        self, pdf_dir, fixture_db, default_config
    ):
        t = parse_transcript(pdf_dir / "csse_junior.pdf")
        rec = Recommender(fixture_db, default_config)
        result = rec.recommend(t, target_quarter="AUT", use_llm=False)
        assert len(result.recommendations) > 0

    def test_no_completed_course_recommended(self, pdf_dir, fixture_db, default_config):
        t = parse_transcript(pdf_dir / "csse_junior.pdf")
        rec = Recommender(fixture_db, default_config)
        result = rec.recommend(t, target_quarter="WIN", use_llm=False)

        completed_ids = {c.course_id for c in t.completed}
        rec_ids = {r.course_id for r in result.recommendations}
        overlap = completed_ids & rec_ids
        assert not overlap, f"Recommended already-completed courses: {overlap}"

    def test_no_wip_course_recommended(self, pdf_dir, fixture_db, default_config):
        t = parse_transcript(pdf_dir / "csse_junior.pdf")
        rec = Recommender(fixture_db, default_config)
        result = rec.recommend(t, target_quarter="AUT", use_llm=False)

        wip_ids = {c.course_id for c in t.in_progress}
        rec_ids = {r.course_id for r in result.recommendations}
        assert not (wip_ids & rec_ids), "Recommended in-progress course"

    def test_prereqs_satisfied(self, pdf_dir, fixture_db, default_config):
        """Every recommended course's prereqs must be met by the transcript."""
        t = parse_transcript(pdf_dir / "csse_junior.pdf")
        rec = Recommender(fixture_db, default_config)
        result = rec.recommend(t, target_quarter="WIN", use_llm=False)

        # All recs must exist in the catalog
        for r in result.recommendations:
            row = fixture_db.execute(
                "SELECT 1 FROM courses WHERE course_id = ?", (r.course_id,)
            ).fetchone()
            assert row is not None, f"Recommended non-existent course {r.course_id}"

    def test_freshman_gets_safe_recommendations(
        self, pdf_dir, fixture_db, default_config
    ):
        """A freshman with only CSS 142 should not get 300+ level courses."""
        t = parse_transcript(pdf_dir / "freshman_minimal.pdf")
        rec = Recommender(fixture_db, default_config)
        result = rec.recommend(t, target_quarter="WIN", use_llm=False)

        rec_ids = {r.course_id for r in result.recommendations}
        # Should NOT get CSS 342 (needs CSS 143 + STMATH 125)
        assert "CSS 342" not in rec_ids
        assert "CSS 422" not in rec_ids
        assert "CSS 430" not in rec_ids


# ── Test Class: Credit Load Variations ──────────────────────────────────────


class TestCreditLoadVariations:
    """Different credit loads (5, 10, 15, 20) all respected."""

    @pytest.mark.parametrize("load", [5, 10, 15, 20])
    def test_credit_load_respected(self, pdf_dir, fixture_db, default_config, load):
        t = parse_transcript(pdf_dir / "csse_junior.pdf")
        default_config.credit_limits.hard_ceiling = 25
        rec = Recommender(fixture_db, default_config)
        result = rec.recommend(t, target_quarter="WIN", credit_load=load, use_llm=False)
        # total_credits should be within [load-2, load+2] or less
        # (less if not enough eligible courses)
        assert result.total_credits <= load + 2


# ── Test Class: API End-to-End with PDFs ────────────────────────────────────


class TestAPIEndToEndWithPDF:
    """POST /api/parse-transcript → POST /api/recommend via TestClient."""

    @pytest.fixture
    def client(self, monkeypatch, tmp_path):
        from fastapi.testclient import TestClient  # type: ignore
        from capstone.api import app

        # Point the API at a temp DB so local dev databases don't leak into tests.
        monkeypatch.setenv("CAPSTONE_DB", str(tmp_path / "api.db"))
        return TestClient(app)

    @pytest.mark.parametrize("name", ["csse_junior", "freshman_minimal", "edge_cases"])
    def test_parse_and_recommend_via_api(self, client, pdf_dir, name):
        pdf_path = pdf_dir / f"{name}.pdf"

        # Step 1: parse the transcript
        with open(pdf_path, "rb") as f:
            r = client.post(
                "/api/parse-transcript",
                files={"file": (f"{name}.pdf", f, "application/pdf")},
            )
        assert r.status_code == 200, f"Parse failed: {r.text}"
        transcript = r.json()
        assert len(transcript["completed"]) > 0

        # Step 2: get recommendations (no LLM)
        r = client.post(
            "/api/recommend",
            json={
                "transcript": transcript,
                "target_quarter": "AUT",
                "credit_load": 15,
                "top_n": 5,
                "use_llm": False,
            },
        )
        # 200 or 503 (if DB not initialized) — both are valid
        assert r.status_code in (200, 503)
        if r.status_code == 200:
            result = r.json()
            assert result["total_credits"] >= 0

    def test_api_rejects_non_pdf(self, client):
        r = client.post(
            "/api/parse-transcript",
            files={"file": ("test.txt", b"not a pdf", "text/plain")},
        )
        assert r.status_code == 400


# ── Test Class: Grade Semantics ─────────────────────────────────────────────


class TestGradeSemantics:
    """Verify grade-related model methods work correctly."""

    def test_passed_numeric(self):
        c = CompletedCourse(
            course_id="X",
            title="x",
            credits=5.0,
            grade="3.5",
            quarter="AUT",
            year=2024,
        )
        assert c.is_passed

    def test_failed_numeric(self):
        c = CompletedCourse(
            course_id="X",
            title="x",
            credits=5.0,
            grade="0.0",
            quarter="AUT",
            year=2024,
        )
        assert not c.is_passed

    def test_cr_passes(self):
        c = CompletedCourse(
            course_id="X",
            title="x",
            credits=1.0,
            grade="CR",
            quarter="AUT",
            year=2024,
        )
        assert c.is_passed

    def test_s_passes(self):
        c = CompletedCourse(
            course_id="X",
            title="x",
            credits=5.0,
            grade="S",
            quarter="AUT",
            year=2024,
        )
        assert c.is_passed

    def test_w_not_passed(self):
        c = CompletedCourse(
            course_id="X",
            title="x",
            credits=5.0,
            grade="W",
            quarter="AUT",
            year=2024,
        )
        assert not c.is_passed
        assert c.is_withdrawn

    def test_nc_not_passed(self):
        c = CompletedCourse(
            course_id="X",
            title="x",
            credits=5.0,
            grade="NC",
            quarter="AUT",
            year=2024,
        )
        assert not c.is_passed

    def test_prereq_grade_default_2_0(self):
        c = CompletedCourse(
            course_id="X",
            title="x",
            credits=5.0,
            grade="2.0",
            quarter="AUT",
            year=2024,
        )
        assert c.meets_prereq_grade(None)  # default 2.0

    def test_prereq_grade_below_threshold(self):
        c = CompletedCourse(
            course_id="X",
            title="x",
            credits=5.0,
            grade="1.9",
            quarter="AUT",
            year=2024,
        )
        assert not c.meets_prereq_grade("2.0")

    def test_cr_meets_any_prereq(self):
        c = CompletedCourse(
            course_id="X",
            title="x",
            credits=1.0,
            grade="CR",
            quarter="AUT",
            year=2024,
        )
        assert c.meets_prereq_grade("3.5")


# ── Test Class: Transcript Serialization Round-Trip ─────────────────────────


class TestTranscriptSerialization:
    """Verify that a parsed transcript serializes to JSON and back."""

    @pytest.mark.parametrize("name", list(ALL_GENERATORS.keys()))
    def test_json_round_trip(self, pdf_dir, name):
        t = parse_transcript(pdf_dir / f"{name}.pdf")
        # Serialize to JSON dict, then re-validate
        json_dict = t.model_dump()
        t2 = Transcript.model_validate(json_dict)
        assert len(t2.completed) == len(t.completed)
        assert t2.student_name == t.student_name
        assert t2.major == t.major
